apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pyapp
  name: pyapp
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: pyapp
status:
  loadBalancer: {}
