apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pyapp
  name: pyapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pyapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pyapp
    spec:
      containers:
      - image: harbor.apps.cf.tanzutime.com/demo/pyapp:b17.20211123.175602
        imagePullPolicy: Always
        name: pyapp
        resources: {}
status: {}
