apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: basic
spec:
  virtualhost:
    fqdn: pyapp.demo.tanzutime.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: lb
          port: 80
      # - prefix: /
      # services:
      #   - name: frontend
      #     port: 80
