apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: contour
spec:
  virtualhost:
    fqdn: pyapp.demo.tanzutime.com
    # tls:
    #   secretName: pyapp-tls
  routes:
    - conditions:
      - prefix: /
      services:
        - name: pyapp
          port: 80
      # - prefix: /
      # services:
      #   - name: frontend
      #     port: 80
