apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-lb
  name: lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: webpython
  type: LoadBalancer
status:
  loadBalancer: {}
