apiVersion: v1
kind: Service
metadata:
  labels:
    app: pyapp
  name: pyapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: pyapp
  type: LoadBalancer
status:
  loadBalancer: {}
